In [2]:
from sklearn.datasets import make_classification   ## just to create some fake data to play with..
import torch


In [3]:
## creating a synthetic classification dataset ...

X, y = make_classification(
    n_samples=10,   ## number of samples or rows
    n_features=2,    ## number of features or columns
    n_informative=2,   ## number of informative features
    n_redundant=0,    ## number of redundant features
    n_classes=2,     ## number of class
    random_state=42    ##  just for reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
X.shape

(10, 2)

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
y.shape

(10,)

In [8]:
## converting the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [9]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [10]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

### Now Dataset and DataLoader

In [11]:
from torch.utils.data import Dataset, DataLoader

In [13]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels =  labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [14]:
dataset = CustomDataset(X,y)

In [15]:
len(dataset)  ## checking the length ..it will trigger the  __len__ magic method

10

In [16]:
dataset[2]    ### just to check

(tensor([-2.8954,  1.9769]), tensor(0))

In [17]:
dataloader  = DataLoader(dataset,  batch_size=2, shuffle=False) ### this is where we define the batch_size,, shuffle..etc....inbuilt in PyTorch...

In [18]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])


### End here...!