# This is the tutorial based PyTorch notebook..means all the basic stuff is here... operations we can do with tensors etcc

In [2]:
import torch

### Creating a tensor

In [5]:
## using empty

torch.empty(2,4)

tensor([[9.3833e-11, 0.0000e+00, 0.0000e+00, 1.6934e-05],
        [0.0000e+00, 5.2375e+04, 0.0000e+00, 1.6934e-05]])

In [7]:
## using zeros

torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
## using ones

torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
## using rand
torch.rand(2,2)

tensor([[0.9205, 0.1472],
        [0.3287, 0.3892]])

In [12]:
## use of seed

torch.manual_seed(10)
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [13]:
torch.manual_seed(10)
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [14]:
## using tensor (custom tensor)
torch.tensor(([[1,2,3], [4,5,7]]))

tensor([[1, 2, 3],
        [4, 5, 7]])

In [17]:
## arange

torch.arange(2,10,3)

tensor([2, 5, 8])

In [18]:
## linspace
torch.linspace(2,10,3)

tensor([ 2.,  6., 10.])

In [19]:
## eye
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
## full
torch.full((2,2), 3)

tensor([[3, 3],
        [3, 3]])

### Tensor Shapes

In [21]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [22]:
x.shape

torch.Size([2, 3])

In [24]:
## copying tensor of same with different vlaues
torch.empty_like(x)

tensor([[    132184101817824,           873725952,                   0],
        [                  0,                   0, 7235419174270214779]])

In [25]:
## same tensorshape but zero values only

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
## same tensorshape but one values only

torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

### Tensor Data Types

In [27]:
## find data type

x.dtype

torch.int64

In [29]:
## assign data type
y = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

In [30]:
y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
## using to () to change datatype

y.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Mathematical Operations on Tensors

In [34]:
x = torch.rand(2,2)
x

tensor([[0.2139, 0.4118],
        [0.6938, 0.9693]])

In [35]:
## addition
x + 2



tensor([[2.2139, 2.4118],
        [2.6938, 2.9693]])

In [37]:
## division
x / 1

tensor([[0.2139, 0.4118],
        [0.6938, 0.9693]])

In [38]:
## Element Wise Operation

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6178, 0.3304, 0.5479],
        [0.4440, 0.7041, 0.5573]])
tensor([[0.6959, 0.9849, 0.2924],
        [0.4823, 0.6150, 0.4967]])


In [41]:
## add
a + b


tensor([[1.3137, 1.3153, 0.8403],
        [0.9263, 1.3191, 1.0540]])

In [42]:
## multiplication
a * b

tensor([[0.4299, 0.3254, 0.1602],
        [0.2141, 0.4330, 0.2768]])

In [45]:
n = torch.tensor([1,2,3,-5])

## abs value
torch.abs(n)

tensor([1, 2, 3, 5])

In [46]:
## negative
torch.neg(n)

tensor([-1, -2, -3,  5])

In [48]:
m = torch.tensor([1,2,3.7,4.0])

## round
torch.round(m)

tensor([1., 2., 4., 4.])

In [50]:
# ceil
torch.ceil(m)

tensor([1., 2., 4., 4.])

In [51]:
# floor
torch.floor(m)

tensor([1., 2., 3., 4.])

In [52]:
## clamp
torch.clamp(m, min=1, max=3)

tensor([1., 2., 3., 3.])

### Reduction Operation

In [53]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[8, 9, 2],
        [0, 9, 9]])

In [54]:
## sum on whole matrix
torch.sum(e)

tensor(37)

In [55]:
## column wise sum of matrix
torch.sum(e, dim=0)

tensor([ 8, 18, 11])

In [56]:
## row wise sum of matrix
torch.sum(e, dim=1)

tensor([19, 18])

In [61]:
## mean of whole matrix
t = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
torch.mean(t)

tensor(4.)

In [62]:
## mean along column
torch.mean(t, dim=0)

tensor([6.5000, 1.5000, 4.0000])

In [63]:
## max and min
torch.max(t)
torch.min(t)

tensor(0.)

In [64]:
## standard deviation
torch.std(t)

tensor(3.8471)

In [65]:
## variance
torch.var(t)

tensor(14.8000)

In [66]:
## argmax
torch.argmax(t)

tensor(3)

## Matrix Operations

In [67]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[9, 3, 7],
        [9, 5, 2]])
tensor([[9, 6],
        [6, 2],
        [8, 9]])


In [68]:
## matrix multiplication
torch.matmul(f,g)

tensor([[155, 123],
        [127,  82]])

In [70]:
## dot product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])

torch.dot(vec1, vec2)

tensor(32)

In [71]:
## transpose
torch.transpose(f, 0, 1)

tensor([[9, 9],
        [3, 5],
        [7, 2]])

### Comparison Operations

In [72]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 9, 1],
        [9, 2, 1]])
tensor([[2, 9, 7],
        [2, 9, 4]])


In [73]:
# greater than
i > j

tensor([[ True, False, False],
        [ True, False, False]])

### Special Functions

In [74]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 9., 4.],
        [4., 8., 3.]])

In [75]:
# log
torch.log(k)

tensor([[1.3863, 2.1972, 1.3863],
        [1.3863, 2.0794, 1.0986]])

In [76]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 3.0000, 2.0000],
        [2.0000, 2.8284, 1.7321]])

In [77]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9999, 0.9820],
        [0.9820, 0.9997, 0.9526]])

In [78]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.7311, 0.7311],
        [0.5000, 0.2689, 0.2689]])

In [79]:
# relu
torch.relu(k)

tensor([[4., 9., 4.],
        [4., 8., 3.]])

## Inplace Operations

In [80]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1576, 0.8879, 0.9792],
        [0.2627, 0.1800, 0.6750]])
tensor([[0.1424, 0.3790, 0.0055],
        [0.6368, 0.3295, 0.2203]])


In [81]:
## it will overwrite the same memory address of (m)
m.add_(n)

tensor([[0.3000, 1.2669, 0.9847],
        [0.8995, 0.5095, 0.8953]])

In [82]:
m

tensor([[0.3000, 1.2669, 0.9847],
        [0.8995, 0.5095, 0.8953]])

In [83]:
n

tensor([[0.1424, 0.3790, 0.0055],
        [0.6368, 0.3295, 0.2203]])

### Copying Tensor


In [84]:
a = torch.rand(2,3)
a

tensor([[0.1821, 0.3241, 0.7375],
        [0.5283, 0.9306, 0.3213]])

In [85]:
b = a.clone()

In [86]:
a

tensor([[0.1821, 0.3241, 0.7375],
        [0.5283, 0.9306, 0.3213]])

In [87]:
b

tensor([[0.1821, 0.3241, 0.7375],
        [0.5283, 0.9306, 0.3213]])

In [88]:
a[0][0] = 10

In [89]:
a

tensor([[10.0000,  0.3241,  0.7375],
        [ 0.5283,  0.9306,  0.3213]])

In [90]:
b

tensor([[0.1821, 0.3241, 0.7375],
        [0.5283, 0.9306, 0.3213]])

In [91]:
id(a)

132179425699184

In [92]:
id(b)

132179425693232

### Tensor Operations on GPU

In [93]:
torch.cuda.is_available()

True

In [94]:
device = torch.device('cuda')

In [95]:
## creating a new tensor on GPU
torch.rand(2,3, device = device)

tensor([[0.9835, 0.2422, 0.7872],
        [0.0981, 0.6317, 0.2422]], device='cuda:0')

In [96]:
## moving an existing tensor to GPU from CPU

a = torch.rand(2,3)
a.to(device)

tensor([[0.3537, 0.9894, 0.0231],
        [0.3032, 0.1898, 0.9811]], device='cuda:0')

### Reshaping Tensors

In [97]:
a = torch.ones(4,4)

a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [98]:
## reshaping
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [99]:
## flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
b = torch.rand(2,3,4)
b

tensor([[[0.7662, 0.3325, 0.2877, 0.6533],
         [0.3310, 0.6552, 0.2441, 0.1906],
         [0.4875, 0.7936, 0.9259, 0.6105]],

        [[0.2030, 0.7614, 0.6949, 0.7133],
         [0.3333, 0.4325, 0.7307, 0.7065],
         [0.8321, 0.2001, 0.8140, 0.3055]]])

In [101]:
### permute
b.permute(2,0,1)

tensor([[[0.7662, 0.3310, 0.4875],
         [0.2030, 0.3333, 0.8321]],

        [[0.3325, 0.6552, 0.7936],
         [0.7614, 0.4325, 0.2001]],

        [[0.2877, 0.2441, 0.9259],
         [0.6949, 0.7307, 0.8140]],

        [[0.6533, 0.1906, 0.6105],
         [0.7133, 0.7065, 0.3055]]])

In [102]:
## unsqueeze
c = torch.rand(2,3)
c

tensor([[0.4874, 0.2647, 0.3518],
        [0.8371, 0.9271, 0.6741]])

In [109]:
c.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [110]:
# squeeze
d = torch.rand(1,2,3)
d

tensor([[[0.1249, 0.3156, 0.8468],
         [0.3651, 0.0916, 0.6161]]])

In [112]:
d.squeeze(0).shape

torch.Size([2, 3])

### Converting Numpy array to Tensor or Tensor to Np array

In [113]:
import numpy as np

In [114]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [115]:
## converting to numpy array
b = a.numpy()
b

array([1, 2, 3])

In [116]:
## now converting np array to tensor
c = np.array([2,3,4])
c


array([2, 3, 4])

In [117]:
torch.from_numpy(c)

tensor([2, 3, 4])

### End ,.... thanks for sticking